"""updated pet model

Revision ID: 59248b3c7cef
Revises: afaa24fe1eec
Create Date: 2025-12-10 15:22:34.179478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59248b3c7cef'
down_revision: Union[str, Sequence[str], None] = 'afaa24fe1eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('breed', sa.String(length=100), nullable=True))
    op.add_column('pets', sa.Column('color', sa.String(length=100), nullable=False))
    op.add_column('pets', sa.Column('sex', sa.String(length=10), nullable=False))
    op.add_column('pets', sa.Column('age', sa.String(length=50), nullable=True))
    op.add_column('pets', sa.Column('chip_number', sa.String(length=100), nullable=True))
    op.add_column('pets', sa.Column('brand_number', sa.String(length=100), nullable=True))
    op.add_column('pets', sa.Column('found_date', sa.Date(), nullable=False))
    op.add_column('pets', sa.Column('found_time', sa.Time(), nullable=False))
    op.add_column('pets', sa.Column('address', sa.String(length=255), nullable=False))
    op.alter_column('pets', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('pets', 'last_seen')
    op.drop_column('pets', 'created_at')
    op.drop_column('pets', 'photo_url')
    op.drop_column('pets', 'city')
    op.drop_column('pets', 'date_lost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('date_lost', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('pets', sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('last_seen', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('pets', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('pets', 'address')
    op.drop_column('pets', 'found_time')
    op.drop_column('pets', 'found_date')
    op.drop_column('pets', 'brand_number')
    op.drop_column('pets', 'chip_number')
    op.drop_column('pets', 'age')
    op.drop_column('pets', 'sex')
    op.drop_column('pets', 'color')
    op.drop_column('pets', 'breed')
    # ### end Alembic commands ###
