"""add photo_url to pets

Revision ID: 6cf4e1869bf8
Revises: 59248b3c7cef
Create Date: 2025-12-10 18:50:53.534704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf4e1869bf8'
down_revision: Union[str, Sequence[str], None] = '59248b3c7cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'photo_url')
    # ### end Alembic commands ###
