"""UsersPets

Revision ID: afaa24fe1eec
Revises: c988ad2f920b
Create Date: 2025-12-03 23:22:34.634548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afaa24fe1eec'
down_revision: Union[str, Sequence[str], None] = 'c988ad2f920b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('pets', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('pets', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.alter_column('pets', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    pet_status = sa.Enum('lost', 'found', 'returned', 'closed', name='pet_status')
    pet_status.create(op.get_bind())
    op.alter_column(
        'pets',
        'status',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum('lost', 'found', 'returned', 'closed', name='pet_status'),
        existing_nullable=False,
        postgresql_using="status::text::pet_status"
    )
    op.create_foreign_key(None, 'pets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.alter_column('pets', 'status',
               existing_type=sa.Enum('lost', 'found', 'returned', 'closed', name='pet_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('pets', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('pets', 'photo_url')
    op.drop_column('pets', 'owner_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
